#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1497444879                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Stress free budgets

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Julian Ramirez                               
your_link                                 : https://surplusfinance.com                     
your_city                                 : San Francisco                                
email_address                             : hello@surplusfinance.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : julianramirez
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Simple Advice
    description                           : Surplus keeps it simple, we give you 1 number to think about. How much you spend today.
    fontawesome_icon_name                 : wallet

  - title                                 : Simple Setup
    description                           : Just let us know your income, any monthly bills, and how much you want to save. We'll take care of the rest.
    fontawesome_icon_name                 : money-check-alt

  - title                                 : Made For The Real World
    description                           : Splitting a meal with friends? Need to ignore that work expense? We gotcha and will do the right thing.
    fontawesome_icon_name                 : magic

  - title                                 : Easily Share Expenses
    description                           : Easily keep track of shared expenses and get accurate spending advice.
    fontawesome_icon_name                 : users
  
  - title                                 : Automatic Updates
    description                           : Subscribe to Surplus Premium to automate your spending advice, no more manual input!
    fontawesome_icon_name                 : sync
    
  - title                                 : Helpful Notifications
    description                           : Subscribe to Surplus Premium to get notified as your daily spendable changes throughout the day.
    fontawesome_icon_name                 : mobile-alt

  - title                                 : Simple Trends
    description                           : See how your spending is trending with monthly trends.
    fontawesome_icon_name                 : poll

  - title                                 : Dive Deep with Merchant Details
    description                           : Quickly view how much you spend on average with a merchant better understand your spending habits.
    fontawesome_icon_name                 : store-alt

  - title                                 : Easy and Powerful Search (Coming Soon!)
    description                           : Find the transaction your looking for with our simple and powerful search.
    fontawesome_icon_name                 : search-dollar

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown